<!DOCTYPE html>
<html lang="en" class="h-full bg-gray-100">

<head>
    <?php include __DIR__ . '/include/head.phtml'; ?>

</head>

<body class="h-full">
    <div class="min-h-full">
        <nav class="bg-gray-800">
            <div class="mx-auto  max-w-7xl px-4">

                <div class="flex items-center justify-start gap-4 h-16">
                    <a href="/"
                        class="text-white py-2 px-3 leading-lg rounded-md hover:bg-gray-900 transition transition-all duration[0.5]"> 
                        Home
                    </a>
                    <a href="/products"
                        class="text-white py-2 px-3 leading-lg rounded-md hover:bg-gray-900 transition transition-all duration[0.5]">

                        Products
                    </a>
                    <a href="/contact"
                        class="text-white py-2 px-3 leading-lg rounded-md hover:bg-gray-900 transition transition-all duration[0.5]">
                        Contact
                    </a>
                </div>

            </div>
        </nav>

        <header class="bg-white shadow">
            <div class="mx-auto  max-w-7xl px-8 py-6">
                <h1 class="text-3xl leading-9 font-bold text-gray-900">Home</h1>
            </div>
        </header>

        <main>
            <div class="mx-auto  max-w-7xl px-8 py-6" style="padding: 2rem 0;">
                <?php mix('css/app.css') ?>
            </div>
        </main>
    </div> 
</body>

</html>